spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student
    password: 12345
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9090

